services:
  - type: web
    name: erp-login-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
        - package.json
        - erp_login_deploy.js
